[package]
name = "omnius-migrations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
humantime-serde.workspace = true
metrics.workspace = true
omnius-config.workspace = true
omnius-core.workspace = true
omnius-postgres.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
omnius-test-support.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
