services:
  service:
    build:
      context: ..
      dockerfile: ops/Dockerfile
    environment:
      OMNIUS_BIND: 0.0.0.0:3000
      OMNIUS_HEALTH_ADDRESS: 127.0.0.1:3000
    ports:
    - 127.0.0.1:3000:3000
    read_only: true
    tmpfs:
    - /tmp:size=16m,mode=1777
    security_opt:
    - no-new-privileges:true
