[package]
name = "rsk-email"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
base64.workspace = true
futures.workspace = true
humantime-serde.workspace = true
lettre.workspace = true
metrics.workspace = true
minijinja.workspace = true
rsk-config.workspace = true
rsk-core.workspace = true
rsk-health.workspace = true
rsk-jobs-core.workspace = true
rsk-runtime.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true

[lints]
workspace = true
