[package]
name = "omnius-cache-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
metrics.workspace = true
redis.workspace = true
omnius-cache-local.workspace = true
omnius-redis-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
omnius-config.workspace = true
omnius-test-support.workspace = true
tokio.workspace = true

[lints]
workspace = true
