[package]
name = "rsk-jobs-pgmq"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
futures.workspace = true
pgmq.workspace = true
rand_core.workspace = true
rsk-jobs-core.workspace = true
rsk-postgres.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
rsk-config.workspace = true
rsk-test-support.workspace = true
serde.workspace = true
uuid.workspace = true

[lints]
workspace = true
