use std::{collections::BTreeMap, fmt, num::NonZeroU32, sync::Arc, time::Duration};

use async_trait::async_trait;
use omnius_agent_capability_registry::CapabilityKey;
use omnius_inbox::{
    ClaimOutcome as InboxClaimOutcome, InboxEvent, InboxStoreError, PostgresInbox, Producer,
    Retention,
};
use omnius_jobs_core::{
    DomainEvent, EventId, EventLimits, EventName, Job, JobId, TenantId as JobTenantId, Version,
};
use omnius_outbox::{OutboxError, PostgresOutbox};
use serde::Deserialize;
use serde_json::json;
use sha2::{Digest, Sha256};
use sqlx::{PgConnection, PgPool, Row, postgres::PgRow};
use time::OffsetDateTime;
use uuid::Uuid;
use zeroize::Zeroizing;

use crate::{
    AbandonExecution, AbandonOutcome, AtomicCancellation, AtomicCreate, AtomicInputUpdate,
    BudgetReservationRef, CancellationOutcome, ClaimOutcome, CreateOutcome, ExecutionClaim,
    ExpiryBatch, ExpiryReport, InputExchange, InputKey, InputResponses, InputRound,
    InputUpdateOutcome, RepositoryError, RequireInput, SettleExecution, SettlementOutcome,
    StoredTask, TaskBudget, TaskExecution, TaskExecutionJob, TaskFailureCode, TaskGeneration,
    TaskId, TaskIdempotency, TaskIdentity, TaskLease, TaskOutboxIntent, TaskOwner, TaskSnapshot,
    TaskState, TaskStatus, TaskTransition, TaskVersion, TerminalSettlement,
};

const TASK_DOCUMENT_MAX_BYTES: usize = 18 * 1_024 * 1_024;
const INPUT_ROUND_MAX_BYTES: usize = 1_200_000;
const TASK_AGGREGATE_TYPE: &str = "mcp_task";
const INBOX_PRODUCER: &str = "omnius.mcp.tasks.worker";
const INBOX_EVENT_TYPE: &str = "mcp.task.execution-delivery.v1";
const INBOX_RETENTION: Duration = Duration::from_hours(168);
const MAX_KEY_ID_BYTES: usize = 128;
const MAX_ALGORITHM_BYTES: usize = 32;
const MAX_PROTECTED_CIPHERTEXT_BYTES: usize = TASK_DOCUMENT_MAX_BYTES + 1_024;
const PROTECTED_NONCE_BYTES: usize = 12;

/// Safe protected-payload failure without key, plaintext, or ciphertext details.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum TaskPayloadProtectionError {
    /// The configured key provider or cryptographic service is temporarily unavailable.
    #[error("task payload protection is unavailable")]
    Unavailable,
    /// Authentication, metadata validation, or bounded plaintext validation failed.
    #[error("task protected payload is invalid")]
    InvalidPayload,
}

/// Versioned authenticated ciphertext retained by the task repository.
#[derive(Clone)]
pub struct ProtectedTaskPayload {
    key_id: String,
    key_revision: NonZeroU32,
    algorithm: String,
    nonce: [u8; PROTECTED_NONCE_BYTES],
    ciphertext: Vec<u8>,
}

impl ProtectedTaskPayload {
    /// Validates one bounded authenticated-ciphertext envelope.
    ///
    /// # Errors
    ///
    /// Returns [`TaskPayloadProtectionError::InvalidPayload`] for unbounded or malformed metadata,
    /// a zero key revision, or empty/oversized ciphertext.
    pub fn new(
        key_id: String,
        key_revision: u32,
        algorithm: String,
        nonce: [u8; PROTECTED_NONCE_BYTES],
        ciphertext: Vec<u8>,
    ) -> Result<Self, TaskPayloadProtectionError> {
        if !bounded_graphic(&key_id, MAX_KEY_ID_BYTES)
            || !bounded_algorithm(&algorithm)
            || ciphertext.is_empty()
            || ciphertext.len() > MAX_PROTECTED_CIPHERTEXT_BYTES
        {
            return Err(TaskPayloadProtectionError::InvalidPayload);
        }
        let key_revision =
            NonZeroU32::new(key_revision).ok_or(TaskPayloadProtectionError::InvalidPayload)?;
        Ok(Self {
            key_id,
            key_revision,
            algorithm,
            nonce,
            ciphertext,
        })
    }

    /// Borrows the non-secret deployment key identifier.
    #[must_use]
    pub fn key_id(&self) -> &str {
        &self.key_id
    }

    /// Returns the non-zero key revision required to open this payload.
    #[must_use]
    pub const fn key_revision(&self) -> NonZeroU32 {
        self.key_revision
    }

    /// Borrows the authenticated encryption algorithm identifier.
    #[must_use]
    pub fn algorithm(&self) -> &str {
        &self.algorithm
    }

    /// Returns the exact unique nonce generated by the protector.
    #[must_use]
    pub const fn nonce(&self) -> &[u8; PROTECTED_NONCE_BYTES] {
        &self.nonce
    }

    /// Borrows bounded authenticated ciphertext.
    #[must_use]
    pub fn ciphertext(&self) -> &[u8] {
        &self.ciphertext
    }
}

impl fmt::Debug for ProtectedTaskPayload {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ProtectedTaskPayload")
            .field("key_revision", &self.key_revision)
            .field("algorithm", &self.algorithm)
            .field("ciphertext_bytes", &self.ciphertext.len())
            .field("content", &"[REDACTED]")
            .finish_non_exhaustive()
    }
}

/// Required authenticated-encryption boundary for all durable protected task material.
///
/// Implementations must generate a unique 96-bit nonce for every seal under a key revision,
/// authenticate the exact caller-supplied AAD, retain old key revisions for reads, and never log
/// plaintext, AAD, key material, nonces, or ciphertext. There is deliberately no plaintext
/// implementation or repository fallback.
#[async_trait]
pub trait TaskPayloadProtector: Send + Sync {
    /// Seals bounded canonical JSON and returns its versioned authenticated ciphertext.
    async fn seal(
        &self,
        aad: &[u8],
        plaintext: &[u8],
    ) -> Result<ProtectedTaskPayload, TaskPayloadProtectionError>;

    /// Authenticates and opens one payload into zeroizing plaintext storage.
    async fn open(
        &self,
        aad: &[u8],
        payload: &ProtectedTaskPayload,
    ) -> Result<Zeroizing<Vec<u8>>, TaskPayloadProtectionError>;
}

/// PostgreSQL-authoritative MCP Tasks repository with transactional outbox and inbox effects.
#[derive(Clone)]
pub struct PostgresTaskRepository {
    pool: PgPool,
    outbox: PostgresOutbox,
    inbox: PostgresInbox,
    protector: Arc<dyn TaskPayloadProtector>,
}

impl PostgresTaskRepository {
    /// Creates an adapter over the application pool, transactional outbox, and required protector.
    #[must_use]
    pub fn new(
        pool: PgPool,
        outbox: PostgresOutbox,
        protector: Arc<dyn TaskPayloadProtector>,
    ) -> Self {
        Self {
            pool,
            outbox,
            inbox: PostgresInbox::new(),
            protector,
        }
    }

    async fn append_outbox<E: DomainEvent>(
        &self,
        connection: &mut PgConnection,
        intent: &TaskOutboxIntent<E>,
        task_id: TaskId,
        available_at: OffsetDateTime,
    ) -> Result<(), RepositoryError> {
        self.outbox
            .append(
                connection,
                intent.event(),
                TASK_AGGREGATE_TYPE,
                &task_id.to_string(),
                intent.destination(),
                available_at,
                EventLimits::default(),
            )
            .await
            .map(|_| ())
            .map_err(map_outbox_error)
    }

    async fn claim_delivery_receipt(
        &self,
        connection: &mut PgConnection,
        stored: &StoredTask,
        job_id: JobId,
    ) -> Result<DeliveryReceipt, RepositoryError> {
        let event = delivery_inbox_event(stored.snapshot(), job_id)?;
        match self
            .inbox
            .claim_with(connection, event)
            .await
            .map_err(map_inbox_error)?
        {
            InboxClaimOutcome::Claimed(claim) => Ok(DeliveryReceipt::Claimed(claim)),
            InboxClaimOutcome::Duplicate => Ok(DeliveryReceipt::Duplicate),
            InboxClaimOutcome::InProgress | InboxClaimOutcome::Conflict => {
                Err(RepositoryError::Integrity)
            }
        }
    }

    async fn resume_delivery_receipt(
        &self,
        connection: &mut PgConnection,
        stored: &StoredTask,
        job_id: JobId,
    ) -> Result<DeliveryReceipt, RepositoryError> {
        let event = delivery_inbox_event(stored.snapshot(), job_id)?;
        self.inbox
            .resume_with(connection, event)
            .await
            .map(DeliveryReceipt::Claimed)
            .map_err(map_inbox_error)
    }

    async fn release_delivery_receipt(
        &self,
        connection: &mut PgConnection,
        receipt: DeliveryReceipt,
    ) -> Result<(), RepositoryError> {
        let DeliveryReceipt::Claimed(claim) = receipt else {
            return Err(RepositoryError::Integrity);
        };
        self.inbox
            .release_with(connection, claim)
            .await
            .map_err(map_inbox_error)
    }

    async fn complete_delivery_receipt(
        &self,
        connection: &mut PgConnection,
        receipt: DeliveryReceipt,
    ) -> Result<(), RepositoryError> {
        let DeliveryReceipt::Claimed(claim) = receipt else {
            return Err(RepositoryError::Integrity);
        };
        let processed_at = database_now(connection).await?;
        self.inbox
            .complete_with(connection, claim, processed_at)
            .await
            .map_err(map_inbox_error)
    }
}

impl fmt::Debug for PostgresTaskRepository {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PostgresTaskRepository")
            .finish_non_exhaustive()
    }
}

#[async_trait]
impl crate::TaskRepository for PostgresTaskRepository {
    #[expect(
        clippy::too_many_lines,
        reason = "one transaction must keep create deduplication, ciphertext state, audit, and outbox atomic"
    )]
    async fn create_atomic(&self, request: AtomicCreate) -> Result<CreateOutcome, RepositoryError> {
        let (requested, intent) = request.into_parts();
        validate_new_task(&requested, &intent)?;
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let now = database_now(&mut transaction).await?;
        let snapshot = requested
            .snapshot()
            .clone()
            .with_authoritative_creation_time(now)
            .map_err(|_| RepositoryError::Integrity)?;
        let stored = StoredTask::new(snapshot.clone(), requested.execution().clone());
        let owner = snapshot.owner();
        let tenant_id = owner.tenant_id().map(omnius_auth_core::TenantId::as_uuid);
        let idempotency_key_sha256: [u8; 32] =
            Sha256::digest(snapshot.idempotency().key().as_str().as_bytes()).into();
        let generation = counter_to_i64(snapshot.generation().get())?;
        let version = counter_to_i64(snapshot.version().get())?;
        let inserted = sqlx::query_scalar::<_, Uuid>(
            "INSERT INTO mcp_task_idempotency (
                 subject_id, tenant_id, operation, capability_id, capability_version,
                 idempotency_key_sha256, request_fingerprint, task_id, created_at
             ) VALUES ($1, $2, 'tasks/create', $3, $4, $5, $6, $7, $8)
             ON CONFLICT ON CONSTRAINT mcp_task_idempotency_scope_unique DO NOTHING
             RETURNING task_id",
        )
        .bind(owner.subject_id().as_uuid())
        .bind(tenant_id)
        .bind(snapshot.capability().id().as_str())
        .bind(snapshot.capability().version().as_str())
        .bind(idempotency_key_sha256.as_slice())
        .bind(snapshot.idempotency().fingerprint().as_bytes().as_slice())
        .bind(snapshot.task_id().as_uuid())
        .bind(snapshot.created_at())
        .fetch_optional(&mut *transaction)
        .await
        .map_err(map_sqlx_error)?;

        if inserted.is_none() {
            let existing = sqlx::query(
                "SELECT task_id, request_fingerprint
                 FROM mcp_task_idempotency
                 WHERE subject_id = $1
                   AND tenant_id IS NOT DISTINCT FROM $2
                   AND operation = 'tasks/create'
                   AND capability_id = $3
                   AND capability_version = $4
                   AND idempotency_key_sha256 = $5
                 FOR UPDATE",
            )
            .bind(owner.subject_id().as_uuid())
            .bind(tenant_id)
            .bind(snapshot.capability().id().as_str())
            .bind(snapshot.capability().version().as_str())
            .bind(idempotency_key_sha256.as_slice())
            .fetch_optional(&mut *transaction)
            .await
            .map_err(map_sqlx_error)?
            .ok_or(RepositoryError::Integrity)?;
            let fingerprint: Vec<u8> = existing
                .try_get("request_fingerprint")
                .map_err(|_| RepositoryError::Integrity)?;
            if fingerprint.as_slice() != snapshot.idempotency().fingerprint().as_bytes() {
                transaction.commit().await.map_err(map_sqlx_error)?;
                return Ok(CreateOutcome::FingerprintConflict);
            }
            let existing_task_id: Uuid = existing
                .try_get("task_id")
                .map_err(|_| RepositoryError::Integrity)?;
            let row = select_task_for_update(&mut transaction, existing_task_id)
                .await?
                .ok_or(RepositoryError::Integrity)?;
            let record = decode_task_record(self.protector.as_ref(), &row).await?;
            validate_existing_identity(&record.stored, &snapshot)?;
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(CreateOutcome::Existing(record.stored.snapshot().clone()));
        }
        let protected = protect_stored_task(self.protector.as_ref(), &stored).await?;
        record_protected_nonce(&mut transaction, &protected, snapshot.task_id(), "task").await?;

        sqlx::query(
            "INSERT INTO mcp_tasks (
                 task_id, subject_id, tenant_id, capability_id, capability_version,
                 idempotency_key_sha256, request_fingerprint, current_job_id, generation, version,
                 status, cancellation_requested, task_key_id, task_key_revision, task_algorithm,
                 task_nonce, task_ciphertext, created_at, updated_at, expires_at
             ) VALUES (
                 $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
                 $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
             )",
        )
        .bind(snapshot.task_id().as_uuid())
        .bind(owner.subject_id().as_uuid())
        .bind(tenant_id)
        .bind(snapshot.capability().id().as_str())
        .bind(snapshot.capability().version().as_str())
        .bind(idempotency_key_sha256.as_slice())
        .bind(snapshot.idempotency().fingerprint().as_bytes().as_slice())
        .bind(snapshot.current_job_id().as_uuid())
        .bind(generation)
        .bind(version)
        .bind(status_label(snapshot.state().status()))
        .bind(snapshot.cancellation_requested())
        .bind(protected.key_id())
        .bind(i64::from(protected.key_revision().get()))
        .bind(protected.algorithm())
        .bind(protected.nonce().as_slice())
        .bind(protected.ciphertext())
        .bind(snapshot.created_at())
        .bind(snapshot.updated_at())
        .bind(snapshot.expires_at())
        .execute(&mut *transaction)
        .await
        .map_err(map_sqlx_error)?;
        insert_task_event(
            &mut transaction,
            &snapshot,
            "created",
            snapshot.created_at(),
        )
        .await?;
        self.append_outbox(
            &mut transaction,
            &intent,
            snapshot.task_id(),
            snapshot.created_at(),
        )
        .await?;
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(CreateOutcome::Created(snapshot))
    }

    async fn get(
        &self,
        owner: TaskOwner,
        task_id: TaskId,
    ) -> Result<Option<TaskSnapshot>, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row = sqlx::query(
            "SELECT task_id, subject_id, tenant_id, capability_id, capability_version,
                    idempotency_key_sha256, request_fingerprint, current_job_id, generation, version,
                    status, cancellation_requested, task_key_id, task_key_revision,
                    task_algorithm, task_nonce, task_ciphertext, created_at, updated_at, expires_at,
                    lease_job_id, lease_generation, lease_version, lease_claimed_at,
                    lease_expires_at
             FROM mcp_tasks
             WHERE task_id = $1
               AND subject_id = $2
               AND tenant_id IS NOT DISTINCT FROM $3
             FOR UPDATE",
        )
        .bind(task_id.as_uuid())
        .bind(owner.subject_id().as_uuid())
        .bind(owner.tenant_id().map(omnius_auth_core::TenantId::as_uuid))
        .fetch_optional(&mut *transaction)
        .await.map_err(map_sqlx_error)?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(None);
        };
        let database_now = database_now(&mut transaction).await?;
        let mut record = decode_task_record(self.protector.as_ref(), &row).await?;
        if !record.stored.snapshot().state().is_terminal()
            && database_now >= record.stored.snapshot().expires_at()
        {
            let receipt = if record.lease.is_some() {
                Some(
                    self.resume_delivery_receipt(
                        &mut transaction,
                        &record.stored,
                        record.stored.snapshot().current_job_id(),
                    )
                    .await?,
                )
            } else {
                None
            };
            let current = record.stored.snapshot();
            let next = current
                .transitioned(
                    current.version(),
                    TaskTransition::Fail(TaskFailureCode::Expired),
                    database_now,
                )
                .map_err(|_| RepositoryError::Integrity)?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                current.version(),
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, "expired", database_now).await?;
            if let Some(receipt) = receipt {
                self.complete_delivery_receipt(&mut transaction, receipt)
                    .await?;
            }
            record.stored = stored;
        }
        let snapshot = record.stored.snapshot().clone();
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(Some(snapshot))
    }

    #[expect(
        clippy::too_many_lines,
        reason = "one transaction must keep input CAS, protected history, state, audit, and outbox atomic"
    )]
    async fn update_input_atomic(
        &self,
        request: AtomicInputUpdate,
    ) -> Result<InputUpdateOutcome, RepositoryError> {
        let (
            owner,
            task_id,
            expected_version,
            expected_generation,
            expected_round,
            responses,
            resume_intent,
            _requested_at,
        ) = request.into_parts();
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row = select_owned_task_for_update(&mut transaction, owner, task_id).await?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(InputUpdateOutcome::NotFound);
        };
        let now = database_now(&mut transaction).await?;
        let record = decode_task_record(self.protector.as_ref(), &row).await?;
        let snapshot = record.stored.snapshot().clone();
        if snapshot.version() != expected_version || snapshot.generation() != expected_generation {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(InputUpdateOutcome::Acknowledged(snapshot));
        }
        let TaskState::InputRequired { round } = snapshot.state() else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(InputUpdateOutcome::Acknowledged(snapshot));
        };
        if round.number() != expected_round {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(InputUpdateOutcome::Acknowledged(snapshot));
        }
        if now >= snapshot.expires_at() {
            let next = snapshot
                .transitioned(
                    snapshot.version(),
                    TaskTransition::Fail(TaskFailureCode::Expired),
                    now,
                )
                .map_err(|_| RepositoryError::Integrity)?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                snapshot.version(),
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, "expired", now).await?;
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(InputUpdateOutcome::Acknowledged(next));
        }
        let update = round.apply(&responses);
        if !update.changed() {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(InputUpdateOutcome::Acknowledged(snapshot));
        }

        if update.complete() {
            validate_resume_intent(&snapshot, &resume_intent)?;
            let answered_round = update.into_round();
            let resume_job = resume_intent.event().data().job();
            let next = snapshot
                .transitioned(
                    expected_version,
                    TaskTransition::Resume {
                        answered_round: answered_round.clone(),
                        job_id: resume_job.id(),
                        generation: resume_job.payload().generation(),
                    },
                    now,
                )
                .map_err(|_| RepositoryError::Integrity)?;
            insert_input_history(
                self.protector.as_ref(),
                &mut transaction,
                &next,
                expected_generation,
                &answered_round,
            )
            .await?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                expected_version,
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, "resumed", now).await?;
            self.append_outbox(&mut transaction, &resume_intent, task_id, now)
                .await?;
            transaction.commit().await.map_err(map_sqlx_error)?;
            Ok(InputUpdateOutcome::Resumed(next))
        } else {
            let next = snapshot
                .transitioned(
                    expected_version,
                    TaskTransition::RecordInput(update.into_round()),
                    now,
                )
                .map_err(|_| RepositoryError::Integrity)?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                expected_version,
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, "input_recorded", now).await?;
            transaction.commit().await.map_err(map_sqlx_error)?;
            Ok(InputUpdateOutcome::Acknowledged(next))
        }
    }

    #[expect(
        clippy::too_many_lines,
        reason = "one transaction keeps cancellation, stale receipt finalization, state, audit, and outbox atomic"
    )]
    async fn cancel_atomic(
        &self,
        request: AtomicCancellation,
    ) -> Result<CancellationOutcome, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row =
            select_owned_task_for_update(&mut transaction, request.owner(), request.task_id())
                .await?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(CancellationOutcome::NotFound);
        };
        let now = database_now(&mut transaction).await?;
        let record = decode_task_record(self.protector.as_ref(), &row).await?;
        let snapshot = record.stored.snapshot().clone();
        if snapshot.version() != request.expected_version()
            || snapshot.generation() != request.expected_generation()
        {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(CancellationOutcome::Stale(snapshot));
        }
        if snapshot.state().is_terminal() {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(CancellationOutcome::Terminal(snapshot));
        }
        if snapshot.cancellation_requested() {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(CancellationOutcome::AlreadyRequested(snapshot));
        }
        if now >= snapshot.expires_at() {
            let receipt = if record.lease.is_some() {
                Some(
                    self.resume_delivery_receipt(
                        &mut transaction,
                        &record.stored,
                        snapshot.current_job_id(),
                    )
                    .await?,
                )
            } else {
                None
            };
            let next = snapshot
                .transitioned(
                    snapshot.version(),
                    TaskTransition::Fail(TaskFailureCode::Expired),
                    now,
                )
                .map_err(|_| RepositoryError::Integrity)?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                snapshot.version(),
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, "expired", now).await?;
            if let Some(receipt) = receipt {
                self.complete_delivery_receipt(&mut transaction, receipt)
                    .await?;
            }
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(CancellationOutcome::Terminal(next));
        }
        validate_cancellation_intent(&snapshot, request.cancellation_intent())?;
        let leased = record.lease.is_some_and(|lease| {
            lease.job_id == snapshot.current_job_id()
                && lease.generation == snapshot.generation()
                && lease.expires_at > now
        });
        let terminal_receipt = if !leased && record.lease.is_some() {
            Some(
                self.resume_delivery_receipt(
                    &mut transaction,
                    &record.stored,
                    snapshot.current_job_id(),
                )
                .await?,
            )
        } else {
            None
        };
        let transition = if leased {
            TaskTransition::RequestCancellation
        } else {
            TaskTransition::Cancel
        };
        let next = snapshot
            .transitioned(snapshot.version(), transition, now)
            .map_err(|_| RepositoryError::Integrity)?;
        let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
        persist_task(
            self.protector.as_ref(),
            &mut transaction,
            &stored,
            snapshot.version(),
            if leased {
                record.lease
            } else {
                LeaseFence::none()
            },
        )
        .await?;
        insert_task_event(
            &mut transaction,
            &next,
            if leased {
                "cancellation_requested"
            } else {
                "cancelled"
            },
            now,
        )
        .await?;
        if let Some(receipt) = terminal_receipt {
            self.complete_delivery_receipt(&mut transaction, receipt)
                .await?;
        }
        self.append_outbox(
            &mut transaction,
            request.cancellation_intent(),
            snapshot.task_id(),
            now,
        )
        .await?;
        transaction.commit().await.map_err(map_sqlx_error)?;
        if leased {
            Ok(CancellationOutcome::Signalled(next))
        } else {
            Ok(CancellationOutcome::Cancelled(next))
        }
    }

    async fn claim_execution(
        &self,
        claim: ExecutionClaim,
    ) -> Result<ClaimOutcome, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row = select_task_for_update(&mut transaction, claim.task_id().as_uuid()).await?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(ClaimOutcome::NotFound);
        };
        let now = database_now(&mut transaction).await?;
        let record = decode_task_record(self.protector.as_ref(), &row).await?;
        let snapshot = record.stored.snapshot().clone();
        if snapshot.current_job_id() != claim.job_id()
            || snapshot.generation() != claim.generation()
            || !matches!(snapshot.state(), TaskState::Working)
        {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(ClaimOutcome::Stale);
        }
        if record.lease.is_some_and(|lease| lease.expires_at > now) {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(ClaimOutcome::Stale);
        }

        if now >= snapshot.expires_at() || snapshot.cancellation_requested() {
            let receipt = if record.lease.is_some() {
                self.resume_delivery_receipt(&mut transaction, &record.stored, claim.job_id())
                    .await?
            } else {
                self.claim_delivery_receipt(&mut transaction, &record.stored, claim.job_id())
                    .await?
            };
            if matches!(receipt, DeliveryReceipt::Duplicate) {
                transaction.commit().await.map_err(map_sqlx_error)?;
                return Ok(ClaimOutcome::Stale);
            }
            let transition = if now >= snapshot.expires_at() {
                TaskTransition::Fail(TaskFailureCode::Expired)
            } else {
                TaskTransition::Cancel
            };
            let next = snapshot
                .transitioned(snapshot.version(), transition, now)
                .map_err(|_| RepositoryError::Integrity)?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                snapshot.version(),
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, terminal_event_kind(&next), now).await?;
            self.complete_delivery_receipt(&mut transaction, receipt)
                .await?;
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(ClaimOutcome::Inactive);
        }

        if record.lease.is_some() {
            let stale_receipt = self
                .resume_delivery_receipt(&mut transaction, &record.stored, claim.job_id())
                .await?;
            self.release_delivery_receipt(&mut transaction, stale_receipt)
                .await?;
        }
        let receipt = self
            .claim_delivery_receipt(&mut transaction, &record.stored, claim.job_id())
            .await?;
        if matches!(receipt, DeliveryReceipt::Duplicate) {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(ClaimOutcome::Stale);
        }
        let history =
            load_input_history(self.protector.as_ref(), &mut transaction, &snapshot).await?;
        let timeout = time::Duration::try_from(TaskExecutionJob::POLICY.timeout())
            .map_err(|_| RepositoryError::Integrity)?;
        let lease = Some(LeaseFence {
            job_id: claim.job_id(),
            generation: claim.generation(),
            version: snapshot.version(),
            claimed_at: now,
            expires_at: now.saturating_add(timeout).min(snapshot.expires_at()),
        });
        persist_lease(
            &mut transaction,
            snapshot.task_id(),
            snapshot.version(),
            lease,
        )
        .await?;
        insert_task_event(&mut transaction, &snapshot, "execution_claimed", now).await?;
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(ClaimOutcome::Leased(TaskLease::new(
            record.stored,
            snapshot.version(),
            now,
            history,
        )))
    }

    async fn abandon_execution(
        &self,
        claim: AbandonExecution,
    ) -> Result<AbandonOutcome, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row = select_task_for_update(&mut transaction, claim.task_id().as_uuid()).await?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(AbandonOutcome::NotFound);
        };
        let now = database_now(&mut transaction).await?;
        let record = decode_task_record(self.protector.as_ref(), &row).await?;
        let snapshot = record.stored.snapshot().clone();
        let exact_lease = record.lease.is_some_and(|lease| {
            lease.job_id == claim.job_id()
                && lease.generation == claim.generation()
                && lease.version == claim.expected_version()
                && lease.claimed_at == claim.lease_claimed_at()
        });
        if !exact_lease
            || snapshot.current_job_id() != claim.job_id()
            || snapshot.generation() != claim.generation()
        {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(AbandonOutcome::Stale);
        }
        let cancellation_advanced = snapshot.cancellation_requested()
            && matches!(snapshot.state(), TaskState::Working)
            && snapshot.version().get() == claim.expected_version().get().saturating_add(1);
        if snapshot.version() != claim.expected_version() && !cancellation_advanced {
            return Err(RepositoryError::Integrity);
        }
        let receipt = self
            .resume_delivery_receipt(&mut transaction, &record.stored, claim.job_id())
            .await?;
        if snapshot.version() == claim.expected_version() {
            self.release_delivery_receipt(&mut transaction, receipt)
                .await?;
            persist_lease(
                &mut transaction,
                snapshot.task_id(),
                snapshot.version(),
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &snapshot, "execution_released", now).await?;
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(AbandonOutcome::Released);
        }
        let next = snapshot
            .transitioned(snapshot.version(), TaskTransition::Cancel, now)
            .map_err(|_| RepositoryError::Integrity)?;
        let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
        persist_task(
            self.protector.as_ref(),
            &mut transaction,
            &stored,
            snapshot.version(),
            LeaseFence::none(),
        )
        .await?;
        insert_task_event(&mut transaction, &next, "cancelled", now).await?;
        self.complete_delivery_receipt(&mut transaction, receipt)
            .await?;
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(AbandonOutcome::Cancelled)
    }

    async fn require_input(
        &self,
        request: RequireInput,
    ) -> Result<SettlementOutcome, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row = select_task_for_update(&mut transaction, request.task_id().as_uuid()).await?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(SettlementOutcome::NotFound);
        };
        let now = database_now(&mut transaction).await?;
        let record = decode_task_record(self.protector.as_ref(), &row).await?;
        let snapshot = record.stored.snapshot().clone();
        let exact_lease = record.lease.is_some_and(|lease| {
            lease.job_id == request.job_id()
                && lease.generation == request.generation()
                && lease.version == request.expected_version()
                && lease.claimed_at == request.lease_claimed_at()
        });
        if !exact_lease
            || snapshot.generation() != request.generation()
            || snapshot.version() != request.expected_version()
            || snapshot.current_job_id() != request.job_id()
            || !matches!(snapshot.state(), TaskState::Working)
            || snapshot.cancellation_requested()
            || now >= snapshot.expires_at()
        {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(SettlementOutcome::Stale);
        }
        validate_new_input_keys(&mut transaction, request.task_id(), request.round()).await?;
        let receipt = self
            .resume_delivery_receipt(&mut transaction, &record.stored, request.job_id())
            .await?;
        let next = snapshot
            .transitioned(
                request.expected_version(),
                TaskTransition::RequireInput(request.round().clone()),
                now,
            )
            .map_err(|_| RepositoryError::Integrity)?;
        let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
        persist_task(
            self.protector.as_ref(),
            &mut transaction,
            &stored,
            snapshot.version(),
            LeaseFence::none(),
        )
        .await?;
        insert_task_event(&mut transaction, &next, "input_required", now).await?;
        self.complete_delivery_receipt(&mut transaction, receipt)
            .await?;
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(SettlementOutcome::Applied(next))
    }

    async fn settle_execution(
        &self,
        settlement: SettleExecution,
    ) -> Result<SettlementOutcome, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let row = select_task_for_update(&mut transaction, settlement.task_id().as_uuid()).await?;
        let Some(row) = row else {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(SettlementOutcome::NotFound);
        };
        let now = database_now(&mut transaction).await?;
        let record = decode_task_record(self.protector.as_ref(), &row).await?;
        let snapshot = record.stored.snapshot().clone();
        let exact_lease = record.lease.is_some_and(|lease| {
            lease.job_id == settlement.job_id()
                && lease.generation == settlement.generation()
                && lease.version == settlement.expected_version()
                && lease.claimed_at == settlement.lease_claimed_at()
        });
        let cancellation_advanced = snapshot.cancellation_requested()
            && snapshot.version().get() == settlement.expected_version().get().saturating_add(1);
        if !exact_lease
            || snapshot.current_job_id() != settlement.job_id()
            || snapshot.generation() != settlement.generation()
            || !matches!(snapshot.state(), TaskState::Working)
            || (snapshot.version() != settlement.expected_version() && !cancellation_advanced)
        {
            transaction.commit().await.map_err(map_sqlx_error)?;
            return Ok(SettlementOutcome::Stale);
        }
        let receipt = self
            .resume_delivery_receipt(&mut transaction, &record.stored, settlement.job_id())
            .await?;
        let transition = if now >= snapshot.expires_at() {
            TaskTransition::Fail(TaskFailureCode::Expired)
        } else {
            match settlement.settlement() {
                TerminalSettlement::Completed(result) => TaskTransition::Complete(result.clone()),
                TerminalSettlement::Failed(failure) => TaskTransition::Fail(*failure),
                TerminalSettlement::Cancelled => TaskTransition::Cancel,
            }
        };
        let next = snapshot
            .transitioned(snapshot.version(), transition, now)
            .map_err(|_| RepositoryError::Integrity)?;
        let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
        persist_task(
            self.protector.as_ref(),
            &mut transaction,
            &stored,
            snapshot.version(),
            LeaseFence::none(),
        )
        .await?;
        insert_task_event(&mut transaction, &next, terminal_event_kind(&next), now).await?;
        self.complete_delivery_receipt(&mut transaction, receipt)
            .await?;
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(SettlementOutcome::Applied(next))
    }

    async fn expire_batch(&self, batch: ExpiryBatch) -> Result<ExpiryReport, RepositoryError> {
        let mut transaction = self.pool.begin().await.map_err(map_sqlx_error)?;
        let now = database_now(&mut transaction).await?;
        let rows = sqlx::query(
            "SELECT task_id, subject_id, tenant_id, capability_id, capability_version,
                    idempotency_key_sha256, request_fingerprint, current_job_id, generation, version,
                    status, cancellation_requested, task_key_id, task_key_revision,
                    task_algorithm, task_nonce, task_ciphertext, created_at, updated_at, expires_at,
                    lease_job_id, lease_generation, lease_version, lease_claimed_at,
                    lease_expires_at
             FROM mcp_tasks
             WHERE status IN ('working', 'input_required')
               AND expires_at <= $1
             ORDER BY expires_at, task_id
             LIMIT $2
             FOR UPDATE SKIP LOCKED",
        )
        .bind(now)
        .bind(i64::try_from(batch.limit().get()).map_err(|_| RepositoryError::Integrity)?)
        .fetch_all(&mut *transaction)
        .await.map_err(map_sqlx_error)?;
        let mut expired = Vec::with_capacity(rows.len());
        for row in rows {
            let record = decode_task_record(self.protector.as_ref(), &row).await?;
            let snapshot = record.stored.snapshot().clone();
            if snapshot.state().is_terminal() || snapshot.expires_at() > now {
                return Err(RepositoryError::Integrity);
            }
            let receipt = if record.lease.is_some() {
                Some(
                    self.resume_delivery_receipt(
                        &mut transaction,
                        &record.stored,
                        snapshot.current_job_id(),
                    )
                    .await?,
                )
            } else {
                None
            };
            let next = snapshot
                .transitioned(
                    snapshot.version(),
                    TaskTransition::Fail(TaskFailureCode::Expired),
                    now,
                )
                .map_err(|_| RepositoryError::Integrity)?;
            let stored = StoredTask::new(next.clone(), record.stored.execution().clone());
            persist_task(
                self.protector.as_ref(),
                &mut transaction,
                &stored,
                snapshot.version(),
                LeaseFence::none(),
            )
            .await?;
            insert_task_event(&mut transaction, &next, "expired", now).await?;
            if let Some(receipt) = receipt {
                self.complete_delivery_receipt(&mut transaction, receipt)
                    .await?;
            }
            expired.push(next.task_id());
        }
        let saturated = expired.len() == batch.limit().get();
        transaction.commit().await.map_err(map_sqlx_error)?;
        Ok(ExpiryReport::new(expired, saturated))
    }
}

#[derive(Clone, Copy)]
struct LeaseFence {
    job_id: JobId,
    generation: TaskGeneration,
    version: TaskVersion,
    claimed_at: OffsetDateTime,
    expires_at: OffsetDateTime,
}

impl LeaseFence {
    const fn none() -> Option<Self> {
        None
    }
}

struct TaskRecord {
    stored: StoredTask,
    lease: Option<LeaseFence>,
}

enum DeliveryReceipt {
    Claimed(omnius_inbox::ClaimedInboxEvent),
    Duplicate,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct StoredTaskDocument {
    snapshot: TaskSnapshotDocument,
    execution: TaskExecution,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct TaskSnapshotDocument {
    task_id: TaskId,
    owner: TaskOwner,
    capability: CapabilityKey,
    identity: TaskIdentity,
    idempotency: TaskIdempotency,
    budget: TaskBudget,
    current_job_id: JobId,
    generation: TaskGeneration,
    version: TaskVersion,
    state: TaskState,
    cancellation_requested: bool,
    #[serde(with = "time::serde::rfc3339")]
    created_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339")]
    updated_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339")]
    expires_at: OffsetDateTime,
    poll_interval_ms: u64,
}

fn encode_stored_task(stored: &StoredTask) -> Result<Zeroizing<Vec<u8>>, RepositoryError> {
    validate_stored_consistency(stored)?;
    let document =
        Zeroizing::new(serde_json::to_vec(stored).map_err(|_| RepositoryError::Integrity)?);
    if document.len() > TASK_DOCUMENT_MAX_BYTES {
        return Err(RepositoryError::Integrity);
    }
    Ok(document)
}

fn decode_stored_task(document: &[u8]) -> Result<StoredTask, RepositoryError> {
    if document.len() > TASK_DOCUMENT_MAX_BYTES {
        return Err(RepositoryError::Integrity);
    }
    let decoded: StoredTaskDocument =
        serde_json::from_slice(document).map_err(|_| RepositoryError::Integrity)?;
    let execution_budget = validated_budget(&decoded.execution)?;
    let execution = TaskExecution::new(
        decoded.execution.capability().clone(),
        decoded.execution.tenant_mode(),
        decoded.execution.confirmation(),
        decoded.execution.input().clone(),
        decoded.execution.idempotency_key().clone(),
        execution_budget,
    )
    .map_err(|_| RepositoryError::Integrity)?;
    let snapshot_budget = TaskBudget::new(
        decoded.snapshot.budget.bounds(),
        BudgetReservationRef::new(decoded.snapshot.budget.reservation().as_str().to_owned())
            .map_err(|_| RepositoryError::Integrity)?,
    );
    let generation = TaskGeneration::new(decoded.snapshot.generation.get())
        .map_err(|_| RepositoryError::Integrity)?;
    let version =
        TaskVersion::new(decoded.snapshot.version.get()).map_err(|_| RepositoryError::Integrity)?;
    let snapshot = TaskSnapshot::restore(
        decoded.snapshot.task_id,
        TaskOwner::new(
            decoded.snapshot.owner.subject_id(),
            decoded.snapshot.owner.tenant_id(),
        ),
        decoded.snapshot.capability,
        TaskIdentity::new(
            decoded.snapshot.identity.request_id(),
            decoded.snapshot.identity.correlation_id(),
            decoded.snapshot.identity.causation_id(),
        ),
        TaskIdempotency::new(
            decoded.snapshot.idempotency.key().clone(),
            decoded.snapshot.idempotency.fingerprint(),
        ),
        snapshot_budget,
        decoded.snapshot.current_job_id,
        generation,
        version,
        decoded.snapshot.state,
        decoded.snapshot.cancellation_requested,
        decoded.snapshot.created_at,
        decoded.snapshot.updated_at,
        decoded.snapshot.expires_at,
        decoded.snapshot.poll_interval_ms,
    )
    .map_err(|_| RepositoryError::Integrity)?;
    let stored = StoredTask::new(snapshot, execution);
    validate_stored_consistency(&stored)?;
    Ok(stored)
}

fn validated_budget(execution: &TaskExecution) -> Result<TaskBudget, RepositoryError> {
    let reservation =
        BudgetReservationRef::new(execution.budget().reservation().as_str().to_owned())
            .map_err(|_| RepositoryError::Integrity)?;
    Ok(TaskBudget::new(execution.budget().bounds(), reservation))
}

fn validate_stored_consistency(stored: &StoredTask) -> Result<(), RepositoryError> {
    let snapshot = stored.snapshot();
    let execution = stored.execution();
    let fingerprint =
        crate::RequestFingerprint::for_invocation(execution.capability(), execution.input())
            .map_err(|_| RepositoryError::Integrity)?;
    if snapshot.capability() != execution.capability()
        || snapshot.budget() != execution.budget()
        || snapshot.idempotency().key() != execution.idempotency_key()
        || snapshot.idempotency().fingerprint() != fingerprint
    {
        return Err(RepositoryError::Integrity);
    }
    Ok(())
}

#[derive(Clone, Copy)]
enum PayloadKind {
    Task,
    InputRound,
}

async fn protect_stored_task(
    protector: &dyn TaskPayloadProtector,
    stored: &StoredTask,
) -> Result<ProtectedTaskPayload, RepositoryError> {
    let plaintext = encode_stored_task(stored)?;
    let snapshot = stored.snapshot();
    let aad = payload_aad(
        snapshot.task_id().as_uuid(),
        snapshot.owner().subject_id().as_uuid(),
        snapshot
            .owner()
            .tenant_id()
            .map(omnius_auth_core::TenantId::as_uuid),
        snapshot.capability().id().as_str(),
        snapshot.capability().version().as_str(),
        PayloadKind::Task,
        snapshot.generation().get(),
        snapshot.version().get(),
        0,
    )?;
    let protected = protector
        .seal(&aad, &plaintext)
        .await
        .map_err(map_protection_error)?;
    if protected.ciphertext().len() > MAX_PROTECTED_CIPHERTEXT_BYTES {
        return Err(RepositoryError::Integrity);
    }
    Ok(protected)
}

fn protected_task_columns(row: &PgRow) -> Result<ProtectedTaskPayload, RepositoryError> {
    protected_columns(
        row,
        "task_key_id",
        "task_key_revision",
        "task_algorithm",
        "task_nonce",
        "task_ciphertext",
        MAX_PROTECTED_CIPHERTEXT_BYTES,
    )
}

fn protected_columns(
    row: &PgRow,
    key_id_column: &str,
    key_revision_column: &str,
    algorithm_column: &str,
    nonce_column: &str,
    ciphertext_column: &str,
    max_ciphertext_bytes: usize,
) -> Result<ProtectedTaskPayload, RepositoryError> {
    let key_id: String = row
        .try_get(key_id_column)
        .map_err(|_| RepositoryError::Integrity)?;
    let key_revision: i64 = row
        .try_get(key_revision_column)
        .map_err(|_| RepositoryError::Integrity)?;
    let algorithm: String = row
        .try_get(algorithm_column)
        .map_err(|_| RepositoryError::Integrity)?;
    let nonce: Vec<u8> = row
        .try_get(nonce_column)
        .map_err(|_| RepositoryError::Integrity)?;
    let ciphertext: Vec<u8> = row
        .try_get(ciphertext_column)
        .map_err(|_| RepositoryError::Integrity)?;
    if ciphertext.len() > max_ciphertext_bytes {
        return Err(RepositoryError::Integrity);
    }
    ProtectedTaskPayload::new(
        key_id,
        u32::try_from(key_revision).map_err(|_| RepositoryError::Integrity)?,
        algorithm,
        nonce.try_into().map_err(|_| RepositoryError::Integrity)?,
        ciphertext,
    )
    .map_err(map_protection_error)
}

#[expect(
    clippy::too_many_arguments,
    reason = "every independent authenticated-data identity and fence must remain explicit"
)]
fn payload_aad(
    task_id: Uuid,
    subject_id: Uuid,
    tenant_id: Option<Uuid>,
    capability_id: &str,
    capability_version: &str,
    kind: PayloadKind,
    generation: u64,
    version: u64,
    round_number: u64,
) -> Result<Vec<u8>, RepositoryError> {
    if !bounded_graphic(capability_id, 128)
        || !bounded_graphic(capability_version, 64)
        || generation == 0
        || version == 0
    {
        return Err(RepositoryError::Integrity);
    }
    let mut aad = Vec::with_capacity(192);
    aad.extend_from_slice(b"omnius/mcp-tasks/protected-payload/v1\0");
    aad.extend_from_slice(task_id.as_bytes());
    aad.extend_from_slice(subject_id.as_bytes());
    match tenant_id {
        Some(tenant_id) => {
            aad.push(1);
            aad.extend_from_slice(tenant_id.as_bytes());
        }
        None => aad.push(0),
    }
    append_aad_segment(&mut aad, capability_id.as_bytes())?;
    append_aad_segment(&mut aad, capability_version.as_bytes())?;
    aad.push(match kind {
        PayloadKind::Task => 1,
        PayloadKind::InputRound => 2,
    });
    aad.extend_from_slice(&generation.to_be_bytes());
    aad.extend_from_slice(&version.to_be_bytes());
    aad.extend_from_slice(&round_number.to_be_bytes());
    Ok(aad)
}

fn append_aad_segment(aad: &mut Vec<u8>, value: &[u8]) -> Result<(), RepositoryError> {
    let length = u32::try_from(value.len()).map_err(|_| RepositoryError::Integrity)?;
    aad.extend_from_slice(&length.to_be_bytes());
    aad.extend_from_slice(value);
    Ok(())
}

#[expect(
    clippy::too_many_lines,
    reason = "fail-closed row reconstruction cross-checks every authoritative relational field"
)]
async fn decode_task_record(
    protector: &dyn TaskPayloadProtector,
    row: &PgRow,
) -> Result<TaskRecord, RepositoryError> {
    let task_id: Uuid = row
        .try_get("task_id")
        .map_err(|_| RepositoryError::Integrity)?;
    let subject_id: Uuid = row
        .try_get("subject_id")
        .map_err(|_| RepositoryError::Integrity)?;
    let tenant_id: Option<Uuid> = row
        .try_get("tenant_id")
        .map_err(|_| RepositoryError::Integrity)?;
    let capability_id: String = row
        .try_get("capability_id")
        .map_err(|_| RepositoryError::Integrity)?;
    let capability_version: String = row
        .try_get("capability_version")
        .map_err(|_| RepositoryError::Integrity)?;
    let idempotency_key_sha256: Vec<u8> = row
        .try_get("idempotency_key_sha256")
        .map_err(|_| RepositoryError::Integrity)?;
    let fingerprint: Vec<u8> = row
        .try_get("request_fingerprint")
        .map_err(|_| RepositoryError::Integrity)?;
    let current_job_id: Uuid = row
        .try_get("current_job_id")
        .map_err(|_| RepositoryError::Integrity)?;
    let generation: i64 = row
        .try_get("generation")
        .map_err(|_| RepositoryError::Integrity)?;
    let version: i64 = row
        .try_get("version")
        .map_err(|_| RepositoryError::Integrity)?;
    let generation_value = positive_counter(generation).ok_or(RepositoryError::Integrity)?;
    let version_value = positive_counter(version).ok_or(RepositoryError::Integrity)?;
    let aad = payload_aad(
        task_id,
        subject_id,
        tenant_id,
        &capability_id,
        &capability_version,
        PayloadKind::Task,
        generation_value,
        version_value,
        0,
    )?;
    let protected = protected_task_columns(row)?;
    let plaintext = protector
        .open(&aad, &protected)
        .await
        .map_err(map_protection_error)?;
    if plaintext.len() > TASK_DOCUMENT_MAX_BYTES {
        return Err(RepositoryError::Integrity);
    }
    let stored = decode_stored_task(&plaintext)?;
    let snapshot = stored.snapshot();
    let status: String = row
        .try_get("status")
        .map_err(|_| RepositoryError::Integrity)?;
    let cancellation_requested: bool = row
        .try_get("cancellation_requested")
        .map_err(|_| RepositoryError::Integrity)?;
    let expected_idempotency_key_sha256: [u8; 32] =
        Sha256::digest(snapshot.idempotency().key().as_str().as_bytes()).into();
    let created_at: OffsetDateTime = row
        .try_get("created_at")
        .map_err(|_| RepositoryError::Integrity)?;
    let updated_at: OffsetDateTime = row
        .try_get("updated_at")
        .map_err(|_| RepositoryError::Integrity)?;
    let expires_at: OffsetDateTime = row
        .try_get("expires_at")
        .map_err(|_| RepositoryError::Integrity)?;
    if task_id != snapshot.task_id().as_uuid()
        || subject_id != snapshot.owner().subject_id().as_uuid()
        || tenant_id
            != snapshot
                .owner()
                .tenant_id()
                .map(omnius_auth_core::TenantId::as_uuid)
        || capability_id != snapshot.capability().id().as_str()
        || capability_version != snapshot.capability().version().as_str()
        || idempotency_key_sha256.as_slice() != expected_idempotency_key_sha256.as_slice()
        || fingerprint.as_slice() != snapshot.idempotency().fingerprint().as_bytes()
        || current_job_id != snapshot.current_job_id().as_uuid()
        || generation != counter_to_i64(snapshot.generation().get())?
        || version != counter_to_i64(snapshot.version().get())?
        || status != status_label(snapshot.state().status())
        || cancellation_requested != snapshot.cancellation_requested()
        || created_at != postgres_timestamp(snapshot.created_at())?
        || updated_at != postgres_timestamp(snapshot.updated_at())?
        || expires_at != postgres_timestamp(snapshot.expires_at())?
    {
        return Err(RepositoryError::Integrity);
    }
    let lease_job_id: Option<Uuid> = row
        .try_get("lease_job_id")
        .map_err(|_| RepositoryError::Integrity)?;
    let lease_generation: Option<i64> = row
        .try_get("lease_generation")
        .map_err(|_| RepositoryError::Integrity)?;
    let lease_version: Option<i64> = row
        .try_get("lease_version")
        .map_err(|_| RepositoryError::Integrity)?;
    let lease_claimed_at: Option<OffsetDateTime> = row
        .try_get("lease_claimed_at")
        .map_err(|_| RepositoryError::Integrity)?;
    let lease_expires_at: Option<OffsetDateTime> = row
        .try_get("lease_expires_at")
        .map_err(|_| RepositoryError::Integrity)?;
    let lease = match (
        lease_job_id,
        lease_generation,
        lease_version,
        lease_claimed_at,
        lease_expires_at,
    ) {
        (None, None, None, None, None) => None,
        (Some(job_id), Some(generation), Some(version), Some(claimed_at), Some(expires_at)) => {
            let job_id = JobId::from_uuid(job_id).map_err(|_| RepositoryError::Integrity)?;
            let generation = positive_counter(generation)
                .and_then(|value| TaskGeneration::new(value).ok())
                .ok_or(RepositoryError::Integrity)?;
            let version = positive_counter(version)
                .and_then(|value| TaskVersion::new(value).ok())
                .ok_or(RepositoryError::Integrity)?;
            if claimed_at >= expires_at
                || job_id != snapshot.current_job_id()
                || generation != snapshot.generation()
                || version > snapshot.version()
            {
                return Err(RepositoryError::Integrity);
            }
            Some(LeaseFence {
                job_id,
                generation,
                version,
                claimed_at,
                expires_at,
            })
        }
        _ => return Err(RepositoryError::Integrity),
    };
    if matches!(snapshot.state(), TaskState::Working) {
        match (snapshot.cancellation_requested(), lease) {
            (true, Some(lease))
                if snapshot.version().get()
                    == lease
                        .version
                        .get()
                        .checked_add(1)
                        .ok_or(RepositoryError::Integrity)? => {}
            (false, Some(lease)) if snapshot.version() == lease.version => {}
            (false, None) => {}
            _ => return Err(RepositoryError::Integrity),
        }
    } else if lease.is_some() {
        return Err(RepositoryError::Integrity);
    }
    Ok(TaskRecord { stored, lease })
}

async fn select_task_for_update(
    connection: &mut PgConnection,
    task_id: Uuid,
) -> Result<Option<PgRow>, RepositoryError> {
    sqlx::query(
        "SELECT task_id, subject_id, tenant_id, capability_id, capability_version,
                idempotency_key_sha256, request_fingerprint, current_job_id, generation, version,
                status, cancellation_requested, task_key_id, task_key_revision, task_algorithm,
                task_nonce, task_ciphertext, created_at, updated_at, expires_at, lease_job_id,
                lease_generation, lease_version, lease_claimed_at, lease_expires_at
         FROM mcp_tasks
         WHERE task_id = $1
         FOR UPDATE",
    )
    .bind(task_id)
    .fetch_optional(connection)
    .await
    .map_err(map_sqlx_error)
}

async fn select_owned_task_for_update(
    connection: &mut PgConnection,
    owner: TaskOwner,
    task_id: TaskId,
) -> Result<Option<PgRow>, RepositoryError> {
    sqlx::query(
        "SELECT task_id, subject_id, tenant_id, capability_id, capability_version,
                idempotency_key_sha256, request_fingerprint, current_job_id, generation, version,
                status, cancellation_requested, task_key_id, task_key_revision, task_algorithm,
                task_nonce, task_ciphertext, created_at, updated_at, expires_at, lease_job_id,
                lease_generation, lease_version, lease_claimed_at, lease_expires_at
         FROM mcp_tasks
         WHERE task_id = $1
           AND subject_id = $2
           AND tenant_id IS NOT DISTINCT FROM $3
         FOR UPDATE",
    )
    .bind(task_id.as_uuid())
    .bind(owner.subject_id().as_uuid())
    .bind(owner.tenant_id().map(omnius_auth_core::TenantId::as_uuid))
    .fetch_optional(connection)
    .await
    .map_err(map_sqlx_error)
}

async fn persist_task(
    protector: &dyn TaskPayloadProtector,
    connection: &mut PgConnection,
    stored: &StoredTask,
    expected_version: TaskVersion,
    lease: Option<LeaseFence>,
) -> Result<(), RepositoryError> {
    let snapshot = stored.snapshot();
    let protected = protect_stored_task(protector, stored).await?;
    record_protected_nonce(connection, &protected, snapshot.task_id(), "task").await?;
    let updated = sqlx::query(
        "UPDATE mcp_tasks
         SET current_job_id = $1,
             generation = $2,
             version = $3,
             status = $4,
             cancellation_requested = $5,
             task_key_id = $6,
             task_key_revision = $7,
             task_algorithm = $8,
             task_nonce = $9,
             task_ciphertext = $10,
             updated_at = $11,
             lease_job_id = $12,
             lease_generation = $13,
             lease_version = $14,
             lease_claimed_at = $15,
             lease_expires_at = $16
         WHERE task_id = $17
           AND version = $18",
    )
    .bind(snapshot.current_job_id().as_uuid())
    .bind(counter_to_i64(snapshot.generation().get())?)
    .bind(counter_to_i64(snapshot.version().get())?)
    .bind(status_label(snapshot.state().status()))
    .bind(snapshot.cancellation_requested())
    .bind(protected.key_id())
    .bind(i64::from(protected.key_revision().get()))
    .bind(protected.algorithm())
    .bind(protected.nonce().as_slice())
    .bind(protected.ciphertext())
    .bind(snapshot.updated_at())
    .bind(lease.map(|value| value.job_id.as_uuid()))
    .bind(
        lease
            .map(|value| counter_to_i64(value.generation.get()))
            .transpose()?,
    )
    .bind(
        lease
            .map(|value| counter_to_i64(value.version.get()))
            .transpose()?,
    )
    .bind(lease.map(|value| value.claimed_at))
    .bind(lease.map(|value| value.expires_at))
    .bind(snapshot.task_id().as_uuid())
    .bind(counter_to_i64(expected_version.get())?)
    .execute(connection)
    .await
    .map_err(map_sqlx_error)?;
    if updated.rows_affected() != 1 {
        return Err(RepositoryError::TransactionConflict);
    }
    Ok(())
}
async fn persist_lease(
    connection: &mut PgConnection,
    task_id: TaskId,
    expected_version: TaskVersion,
    lease: Option<LeaseFence>,
) -> Result<(), RepositoryError> {
    let updated = sqlx::query(
        "UPDATE mcp_tasks
         SET lease_job_id = $1,
             lease_generation = $2,
             lease_version = $3,
             lease_claimed_at = $4,
             lease_expires_at = $5
         WHERE task_id = $6
           AND version = $7",
    )
    .bind(lease.map(|value| value.job_id.as_uuid()))
    .bind(
        lease
            .map(|value| counter_to_i64(value.generation.get()))
            .transpose()?,
    )
    .bind(
        lease
            .map(|value| counter_to_i64(value.version.get()))
            .transpose()?,
    )
    .bind(lease.map(|value| value.claimed_at))
    .bind(lease.map(|value| value.expires_at))
    .bind(task_id.as_uuid())
    .bind(counter_to_i64(expected_version.get())?)
    .execute(connection)
    .await
    .map_err(map_sqlx_error)?;
    if updated.rows_affected() != 1 {
        return Err(RepositoryError::TransactionConflict);
    }
    Ok(())
}

async fn record_protected_nonce(
    connection: &mut PgConnection,
    protected: &ProtectedTaskPayload,
    task_id: TaskId,
    payload_kind: &'static str,
) -> Result<(), RepositoryError> {
    sqlx::query(
        "INSERT INTO mcp_task_payload_nonces (
             key_id, key_revision, nonce, task_id, payload_kind, created_at
         ) VALUES ($1, $2, $3, $4, $5, clock_timestamp())",
    )
    .bind(protected.key_id())
    .bind(i64::from(protected.key_revision().get()))
    .bind(protected.nonce().as_slice())
    .bind(task_id.as_uuid())
    .bind(payload_kind)
    .execute(connection)
    .await
    .map_err(map_sqlx_error)?;
    Ok(())
}

async fn insert_task_event(
    connection: &mut PgConnection,
    snapshot: &TaskSnapshot,
    kind: &'static str,
    occurred_at: OffsetDateTime,
) -> Result<(), RepositoryError> {
    sqlx::query(
        "INSERT INTO mcp_task_events (
             task_id, task_version, generation, event_kind, status, occurred_at
         ) VALUES ($1, $2, $3, $4, $5, $6)",
    )
    .bind(snapshot.task_id().as_uuid())
    .bind(counter_to_i64(snapshot.version().get())?)
    .bind(counter_to_i64(snapshot.generation().get())?)
    .bind(kind)
    .bind(status_label(snapshot.state().status()))
    .bind(occurred_at)
    .execute(connection)
    .await
    .map_err(map_sqlx_error)?;
    Ok(())
}

async fn validate_new_input_keys(
    connection: &mut PgConnection,
    task_id: TaskId,
    round: &InputRound,
) -> Result<(), RepositoryError> {
    for key in round.exchanges().keys() {
        let key_digest: [u8; 32] = Sha256::digest(key.as_str().as_bytes()).into();
        let inserted = sqlx::query(
            "INSERT INTO mcp_task_input_keys (
                 task_id, input_key_sha256, first_round, created_at
             ) VALUES ($1, $2, $3, clock_timestamp())
             ON CONFLICT (task_id, input_key_sha256) DO NOTHING",
        )
        .bind(task_id.as_uuid())
        .bind(key_digest.as_slice())
        .bind(counter_to_i64(round.number())?)
        .execute(&mut *connection)
        .await
        .map_err(map_sqlx_error)?;
        if inserted.rows_affected() != 1 {
            return Err(RepositoryError::Integrity);
        }
    }
    Ok(())
}

async fn insert_input_history(
    protector: &dyn TaskPayloadProtector,
    connection: &mut PgConnection,
    snapshot: &TaskSnapshot,
    completed_generation: TaskGeneration,
    round: &InputRound,
) -> Result<(), RepositoryError> {
    let plaintext =
        Zeroizing::new(serde_json::to_vec(round).map_err(|_| RepositoryError::Integrity)?);
    if plaintext.len() > INPUT_ROUND_MAX_BYTES || round.pending().next().is_some() {
        return Err(RepositoryError::Integrity);
    }
    let aad = payload_aad(
        snapshot.task_id().as_uuid(),
        snapshot.owner().subject_id().as_uuid(),
        snapshot
            .owner()
            .tenant_id()
            .map(omnius_auth_core::TenantId::as_uuid),
        snapshot.capability().id().as_str(),
        snapshot.capability().version().as_str(),
        PayloadKind::InputRound,
        completed_generation.get(),
        snapshot.version().get(),
        round.number(),
    )?;
    let protected = protector
        .seal(&aad, &plaintext)
        .await
        .map_err(map_protection_error)?;
    if protected.ciphertext().len() > INPUT_ROUND_MAX_BYTES + 1_024 {
        return Err(RepositoryError::Integrity);
    }
    record_protected_nonce(connection, &protected, snapshot.task_id(), "input_round").await?;
    sqlx::query(
        "INSERT INTO mcp_task_input_rounds (
             task_id, round_number, completed_generation, task_version, round_key_id,
             round_key_revision, round_algorithm, round_nonce, round_ciphertext, completed_at
         ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, clock_timestamp())",
    )
    .bind(snapshot.task_id().as_uuid())
    .bind(counter_to_i64(round.number())?)
    .bind(counter_to_i64(completed_generation.get())?)
    .bind(counter_to_i64(snapshot.version().get())?)
    .bind(protected.key_id())
    .bind(i64::from(protected.key_revision().get()))
    .bind(protected.algorithm())
    .bind(protected.nonce().as_slice())
    .bind(protected.ciphertext())
    .execute(connection)
    .await
    .map_err(map_sqlx_error)?;
    Ok(())
}

async fn load_input_history(
    protector: &dyn TaskPayloadProtector,
    connection: &mut PgConnection,
    snapshot: &TaskSnapshot,
) -> Result<Vec<InputRound>, RepositoryError> {
    let rows = sqlx::query(
        "SELECT round_number, completed_generation, task_version, round_key_id,
                round_key_revision, round_algorithm, round_nonce, round_ciphertext
         FROM mcp_task_input_rounds
         WHERE task_id = $1
         ORDER BY round_number",
    )
    .bind(snapshot.task_id().as_uuid())
    .fetch_all(connection)
    .await
    .map_err(map_sqlx_error)?;
    let expected_count = snapshot
        .generation()
        .get()
        .checked_sub(1)
        .ok_or(RepositoryError::Integrity)?;
    if usize::try_from(expected_count).map_err(|_| RepositoryError::Integrity)? != rows.len() {
        return Err(RepositoryError::Integrity);
    }
    let mut history = Vec::with_capacity(rows.len());
    for (index, row) in rows.into_iter().enumerate() {
        let expected = u64::try_from(index)
            .ok()
            .and_then(|value| value.checked_add(1))
            .ok_or(RepositoryError::Integrity)?;
        let round_number: i64 = row
            .try_get("round_number")
            .map_err(|_| RepositoryError::Integrity)?;
        let completed_generation: i64 = row
            .try_get("completed_generation")
            .map_err(|_| RepositoryError::Integrity)?;
        let task_version: i64 = row
            .try_get("task_version")
            .map_err(|_| RepositoryError::Integrity)?;
        let aad_generation =
            positive_counter(completed_generation).ok_or(RepositoryError::Integrity)?;
        let aad_version = positive_counter(task_version).ok_or(RepositoryError::Integrity)?;
        if positive_counter(round_number) != Some(expected)
            || aad_generation != expected
            || aad_version > snapshot.version().get()
        {
            return Err(RepositoryError::Integrity);
        }
        let aad = payload_aad(
            snapshot.task_id().as_uuid(),
            snapshot.owner().subject_id().as_uuid(),
            snapshot
                .owner()
                .tenant_id()
                .map(omnius_auth_core::TenantId::as_uuid),
            snapshot.capability().id().as_str(),
            snapshot.capability().version().as_str(),
            PayloadKind::InputRound,
            aad_generation,
            aad_version,
            expected,
        )?;
        let protected = protected_columns(
            &row,
            "round_key_id",
            "round_key_revision",
            "round_algorithm",
            "round_nonce",
            "round_ciphertext",
            INPUT_ROUND_MAX_BYTES + 1_024,
        )?;
        let plaintext = protector
            .open(&aad, &protected)
            .await
            .map_err(map_protection_error)?;
        let round = decode_completed_round(&plaintext)?;
        if round.number() != expected {
            return Err(RepositoryError::Integrity);
        }
        history.push(round);
    }
    Ok(history)
}

fn decode_completed_round(document: &[u8]) -> Result<InputRound, RepositoryError> {
    if document.len() > INPUT_ROUND_MAX_BYTES {
        return Err(RepositoryError::Integrity);
    }
    let decoded: InputRound =
        serde_json::from_slice(document).map_err(|_| RepositoryError::Integrity)?;
    let mut exchanges = BTreeMap::new();
    let mut responses = BTreeMap::new();
    for (key, exchange) in decoded.exchanges() {
        let validated_key =
            InputKey::new(key.as_str().to_owned()).map_err(|_| RepositoryError::Integrity)?;
        let pending = InputExchange::pending(exchange.request().clone())
            .map_err(|_| RepositoryError::Integrity)?;
        let response = exchange.response().ok_or(RepositoryError::Integrity)?;
        exchanges.insert(validated_key, pending);
        responses.insert(key.as_str().to_owned(), response.clone());
    }
    let pending = InputRound::new(
        decoded.number(),
        crate::TaskRequestState::new(decoded.request_state().as_str().to_owned())
            .map_err(|_| RepositoryError::Integrity)?,
        exchanges,
    )
    .map_err(|_| RepositoryError::Integrity)?;
    let responses = InputResponses::new(responses).map_err(|_| RepositoryError::Integrity)?;
    let restored = pending.apply(&responses);
    if !restored.changed() || !restored.complete() {
        return Err(RepositoryError::Integrity);
    }
    Ok(restored.into_round())
}

fn delivery_inbox_event(
    snapshot: &TaskSnapshot,
    job_id: JobId,
) -> Result<InboxEvent, RepositoryError> {
    let producer = Producer::try_from(INBOX_PRODUCER).map_err(|_| RepositoryError::Integrity)?;
    let event_id = EventId::from_uuid(job_id.as_uuid()).map_err(|_| RepositoryError::Integrity)?;
    let event_type =
        EventName::try_from(INBOX_EVENT_TYPE.to_owned()).map_err(|_| RepositoryError::Integrity)?;
    let version = Version::new(1).map_err(|_| RepositoryError::Integrity)?;
    let tenant = snapshot
        .owner()
        .tenant_id()
        .map(|value| JobTenantId::try_from(value.to_string()))
        .transpose()
        .map_err(|_| RepositoryError::Integrity)?;
    let payload = serde_json::to_vec(&json!({
        "generation": snapshot.generation().get(),
        "job_id": job_id.to_string(),
        "task_id": snapshot.task_id().to_string(),
    }))
    .map_err(|_| RepositoryError::Integrity)?;
    let retention = Retention::new(INBOX_RETENTION).map_err(|_| RepositoryError::Integrity)?;
    InboxEvent::new(
        producer,
        event_id,
        event_type,
        version,
        tenant.as_ref(),
        snapshot.identity().correlation_id().as_uuid(),
        snapshot
            .identity()
            .causation_id()
            .map(omnius_core::CausationId::as_uuid),
        &payload,
        retention,
    )
    .map_err(|_| RepositoryError::Integrity)
}

fn validate_new_task(
    stored: &StoredTask,
    intent: &TaskOutboxIntent<crate::TaskExecutionRequested>,
) -> Result<(), RepositoryError> {
    validate_stored_consistency(stored)?;
    let snapshot = stored.snapshot();
    if snapshot.generation() != TaskGeneration::INITIAL
        || snapshot.version() != TaskVersion::INITIAL
        || !matches!(snapshot.state(), TaskState::Working)
        || snapshot.cancellation_requested()
        || snapshot.created_at() != snapshot.updated_at()
    {
        return Err(RepositoryError::Integrity);
    }
    validate_execution_intent(snapshot, intent)
}

fn validate_execution_intent(
    snapshot: &TaskSnapshot,
    intent: &TaskOutboxIntent<crate::TaskExecutionRequested>,
) -> Result<(), RepositoryError> {
    let job = intent.event().data().job();
    if job.id() != snapshot.current_job_id()
        || job.payload().task_id() != snapshot.task_id()
        || job.payload().generation() != snapshot.generation()
    {
        return Err(RepositoryError::Integrity);
    }
    validate_event_identity(snapshot, intent.event())
}

fn validate_resume_intent(
    snapshot: &TaskSnapshot,
    intent: &TaskOutboxIntent<crate::TaskExecutionRequested>,
) -> Result<(), RepositoryError> {
    let job = intent.event().data().job();
    if job.payload().task_id() != snapshot.task_id()
        || snapshot.generation().next() != Some(job.payload().generation())
    {
        return Err(RepositoryError::Integrity);
    }
    validate_event_identity(snapshot, intent.event())
}

fn validate_cancellation_intent(
    snapshot: &TaskSnapshot,
    intent: &TaskOutboxIntent<crate::TaskCancellationRequested>,
) -> Result<(), RepositoryError> {
    let job = intent.event().data().job();
    if job.payload().task_id() != snapshot.task_id()
        || job.payload().generation() != snapshot.generation()
    {
        return Err(RepositoryError::Integrity);
    }
    validate_event_identity(snapshot, intent.event())
}

fn validate_event_identity<E: DomainEvent>(
    snapshot: &TaskSnapshot,
    event: &omnius_jobs_core::EventEnvelope<E>,
) -> Result<(), RepositoryError> {
    let expected_tenant = snapshot.owner().tenant_id().map(|value| value.to_string());
    if event.tenant_id().map(JobTenantId::as_str) != expected_tenant.as_deref()
        || event.correlation_id() != snapshot.identity().correlation_id().as_uuid()
        || event.causation_id()
            != snapshot
                .identity()
                .causation_id()
                .map(omnius_core::CausationId::as_uuid)
    {
        return Err(RepositoryError::Integrity);
    }
    Ok(())
}

fn validate_existing_identity(
    existing: &StoredTask,
    requested: &TaskSnapshot,
) -> Result<(), RepositoryError> {
    let snapshot = existing.snapshot();
    if snapshot.owner() != requested.owner()
        || snapshot.capability() != requested.capability()
        || snapshot.idempotency().key() != requested.idempotency().key()
        || snapshot.idempotency().fingerprint() != requested.idempotency().fingerprint()
    {
        return Err(RepositoryError::Integrity);
    }
    Ok(())
}

const fn status_label(status: TaskStatus) -> &'static str {
    match status {
        TaskStatus::Working => "working",
        TaskStatus::InputRequired => "input_required",
        TaskStatus::Completed => "completed",
        TaskStatus::Failed => "failed",
        TaskStatus::Cancelled => "cancelled",
    }
}

fn terminal_event_kind(snapshot: &TaskSnapshot) -> &'static str {
    match snapshot.state() {
        TaskState::Completed { .. } => "completed",
        TaskState::Failed {
            failure: TaskFailureCode::Expired,
        } => "expired",
        TaskState::Failed { .. } => "failed",
        TaskState::Cancelled => "cancelled",
        TaskState::Working | TaskState::InputRequired { .. } => "settled",
    }
}

fn bounded_graphic(value: &str, max_bytes: usize) -> bool {
    !value.is_empty()
        && value.len() <= max_bytes
        && value.is_ascii()
        && value.bytes().all(|byte| byte.is_ascii_graphic())
}

fn bounded_algorithm(value: &str) -> bool {
    let bytes = value.as_bytes();
    !bytes.is_empty()
        && bytes.len() <= MAX_ALGORITHM_BYTES
        && bytes[0].is_ascii_lowercase()
        && bytes
            .iter()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-'))
}

fn map_protection_error(error: TaskPayloadProtectionError) -> RepositoryError {
    match error {
        TaskPayloadProtectionError::Unavailable => RepositoryError::Unavailable,
        TaskPayloadProtectionError::InvalidPayload => RepositoryError::Integrity,
    }
}

fn positive_counter(value: i64) -> Option<u64> {
    u64::try_from(value).ok().filter(|value| *value > 0)
}

async fn database_now(connection: &mut PgConnection) -> Result<OffsetDateTime, RepositoryError> {
    sqlx::query_scalar("SELECT clock_timestamp()")
        .fetch_one(connection)
        .await
        .map_err(map_sqlx_error)
}

fn postgres_timestamp(value: OffsetDateTime) -> Result<OffsetDateTime, RepositoryError> {
    let nanoseconds = value.unix_timestamp_nanos();
    let microseconds = nanoseconds.div_euclid(1_000);
    OffsetDateTime::from_unix_timestamp_nanos(microseconds * 1_000)
        .map_err(|_| RepositoryError::Integrity)
}

fn counter_to_i64(value: u64) -> Result<i64, RepositoryError> {
    i64::try_from(value).map_err(|_| RepositoryError::Integrity)
}

fn map_outbox_error(error: OutboxError) -> RepositoryError {
    match error {
        OutboxError::Database => RepositoryError::Unavailable,
        OutboxError::InvalidAggregateType
        | OutboxError::InvalidAggregateId
        | OutboxError::InvalidEventVersion
        | OutboxError::Encode
        | OutboxError::InvalidRetryDelay
        | OutboxError::LostLease => RepositoryError::Integrity,
    }
}

fn map_inbox_error(error: InboxStoreError) -> RepositoryError {
    match error {
        InboxStoreError::Transient => RepositoryError::TransactionConflict,
        InboxStoreError::Unavailable => RepositoryError::Unavailable,
        InboxStoreError::CorruptInput
        | InboxStoreError::ClaimLost
        | InboxStoreError::InvalidProcessedAt
        | InboxStoreError::ConstraintViolation
        | InboxStoreError::CorruptData => RepositoryError::Integrity,
    }
}

fn map_sqlx_error(error: sqlx::Error) -> RepositoryError {
    match error {
        sqlx::Error::Database(database) => match database.code().as_deref() {
            Some("40001" | "40P01" | "55P03") => RepositoryError::TransactionConflict,
            Some("55000") => RepositoryError::Integrity,
            Some(code) if code.starts_with("22") || code.starts_with("23") => {
                RepositoryError::Integrity
            }
            _ => RepositoryError::Unavailable,
        },
        sqlx::Error::RowNotFound
        | sqlx::Error::ColumnNotFound(_)
        | sqlx::Error::ColumnDecode { .. } => RepositoryError::Integrity,
        _ => RepositoryError::Unavailable,
    }
}
