[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
csv.workspace = true
jsonschema.workspace = true
regex.workspace = true
omnius-api-server.workspace = true
omnius-email.workspace = true
omnius-openapi.workspace = true
omnius-realtime-core.workspace = true
omnius-realtime-sse.workspace = true
omnius-realtime-websocket.workspace = true
omnius-generator.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
toml.workspace = true
walkdir.workspace = true

[dev-dependencies]
omnius-test-support.workspace = true

[lints]
workspace = true
