[package]
name = "omnius-events-nats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-nats.workspace = true
bytes.workspace = true
futures.workspace = true
humantime-serde.workspace = true
metrics.workspace = true
omnius-config.workspace = true
omnius-core.workspace = true
omnius-health.workspace = true
omnius-jobs-core.workspace = true
omnius-outbox.workspace = true
omnius-runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
omnius-migrations.workspace = true
omnius-postgres.workspace = true
sqlx.workspace = true
omnius-test-support.workspace = true

[lints]
workspace = true
