[package]
name = "{{project-name}}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "service"

[dependencies]
axum.workspace = true
clap.workspace = true
garde.workspace = true
humantime-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
service-kit.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
serde.workspace = true
toml.workspace = true

[dev-dependencies]
http-body-util.workspace = true
service-kit = { workspace = true, features = ["test-support"] }
tower.workspace = true

[lints]
workspace = true
