[package]
name = "{{project-name}}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "service"

[dependencies]
axum.workspace = true
omnius-http.workspace = true
serde.workspace = true
serde_json.workspace = true
service-kit = { package = "{{project-name}}-kit", path = "../../crates/service-kit" }
tokio.workspace = true
toml.workspace = true

[build-dependencies]
serde.workspace = true
toml.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true

[lints]
workspace = true
