[package]
name = "omnius-webhooks-svix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chrono.workspace = true
futures.workspace = true
humantime-serde.workspace = true
js_option.workspace = true
metrics.workspace = true
omnius-config.workspace = true
omnius-core.workspace = true
omnius-health.workspace = true
omnius-outbox.workspace = true
omnius-outbound-http.workspace = true
omnius-runtime.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision", "preserve_order", "raw_value"] }
svix.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true

[lints]
workspace = true
