[package]
name = "rsk-webhooks-svix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chrono.workspace = true
futures.workspace = true
humantime-serde.workspace = true
js_option.workspace = true
metrics.workspace = true
rsk-config.workspace = true
rsk-core.workspace = true
rsk-health.workspace = true
rsk-outbox.workspace = true
rsk-outbound-http.workspace = true
rsk-runtime.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision", "preserve_order", "raw_value"] }
svix.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
url.workspace = true

[lints]
workspace = true
