schema_version = 2
service = "{{project-name}}"
ownership = []
managed_regions = []

[framework]
version = "{{ kit_version }}"
repository = "https://github.com/bmanturner/omnius.git"
revision = "{{ release_revision }}"

[profile]
id = "{{ profile }}"
version = "{{ kit_version }}"
additions = []
removals = []

{% for module in modules %}
[[modules]]
id = "{{ module }}"
version = "0.1.0"

{% endfor %}
{% for provider in providers %}
[[providers]]
slot = "{{ provider.slot }}"
module = "{{ provider.module }}"

{% endfor %}
