[package]
name = "omnius-events-redis-ephemeral"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
humantime-serde.workspace = true
metrics.workspace = true
redis.workspace = true
omnius-core.workspace = true
omnius-redis-core.workspace = true
omnius-runtime.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
omnius-config.workspace = true
omnius-test-support.workspace = true
serde_json.workspace = true

[lints]
workspace = true
