packages:
  - compat/web-w0
  - packages/*
  - web

sharedWorkspaceLockfile: true
preferWorkspacePackages: true
saveExact: true
strictPeerDependencies: true
overrides:
  js-yaml@4.3.1: 4.3.2
allowBuilds:
  esbuild: true
  msw: false
