[package]
name = "omnius-phase0-compatibility"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
apalis.workspace = true
apalis-redis.workspace = true
axum.workspace = true
axum-login.workspace = true
fred.workspace = true
hyper.workspace = true
jsonschema.workspace = true
jsonwebtoken.workspace = true
oauth2.workspace = true
openidconnect.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry_sdk.workspace = true
pgmq.workspace = true
redis.workspace = true
redis-apalis.workspace = true
reqwest.workspace = true
rig-agent.workspace = true
rig-bedrock.workspace = true
rig-core.workspace = true
rig-vertexai.workspace = true
rmcp = { workspace = true, features = ["server", "transport-streamable-http-server", "elicitation", "request-state"] }
rustls.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tower-sessions.workspace = true
tower-sessions-redis-store.workspace = true
tower-sessions-sqlx-store.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
webpki-roots.workspace = true
