[package]
name = "rsk-reference-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
metrics.workspace = true
rsk-postgres.workspace = true
rsk-reference-domain.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
rsk-config.workspace = true
rsk-migrations.workspace = true
rsk-test-support.workspace = true
tokio.workspace = true

[lints]
workspace = true
