[package]
name = "omnius-reference-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
metrics.workspace = true
omnius-pagination.workspace = true
omnius-postgres.workspace = true
omnius-reference-domain.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
omnius-config.workspace = true
omnius-migrations.workspace = true
omnius-test-support.workspace = true
tokio.workspace = true

[lints]
workspace = true
