[package]
name = "rsk-jobs-apalis-redis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
apalis = { workspace = true, features = ["limit"] }
apalis-redis = { workspace = true, features = ["tokio-comp"] }
futures.workspace = true
rand_core.workspace = true
redis-apalis.workspace = true
rsk-config.workspace = true
rsk-jobs-core.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
rsk-test-support.workspace = true
uuid.workspace = true

[lints]
workspace = true
