[package]
name = "omnius-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
garde.workspace = true
humantime-serde.workspace = true
metrics.workspace = true
omnius-config.workspace = true
omnius-core.workspace = true
omnius-health.workspace = true
omnius-runtime.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
omnius-test-support.workspace = true

[lints]
workspace = true
